baseURL = "https://travelinkeo13.netlify.app"
disableLanguages = []
disqusShortname = ""
paginate = "6"
summaryLength = "15"
theme = "meghna-hugo"
title = "Travelinkeo"
[Languages.en]
contentDir = "content/english"
copyright = "copyright &copy; 2020 [Travelinkeo](https://#) all right reserved"
home = "Inicio"
languageCode = "es-ve"
languageName = "Es"
weight = 1
[Languages.fr]
contentDir = "content/french"
copyright = "copyright et copie; 2019 [gethugothemes] (https://gethugothemes.com) tous droits réservés"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[menu.main]]
URL = "contact"
name = "Contacto"
weight = 7
[[menu.main]]
URL = "pricing"
name = "Precios"
weight = 5
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 6
[[menu.main]]
URL = "team"
name = "Equipo "
weight = 4
[[menu.main]]
URL = "portfolio"
name = "Portafolio"
weight = 3
[[menu.main]]
URL = "services"
name = "Servicios"
weight = 2
[[menu.main]]
URL = "about"
name = "Quienes Somos"
weight = 1
[params]
author = "Travelinkeo"
description = "Responsive Multipurpose Parallax HTML5 Template"
google_analitycs_id = ""
logo = "images/Logotipo2Blanco.png"
post_share = true
[params.map]
enable = true
gmap_api = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3923.2842838850556!2d-66.90638158468684!3d10.478240992524299!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8c2a5f352889f1c3%3A0x61f98b2f3d59ab1a!2sServicios%20Travelinkeo%201331%20C.A.!5e0!3m2!1ses!2sve!4v1589651806431!5m2!1ses!2sve"
map_latitude = "10.478312"
map_longitude = "-66.904139"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/fontawesome-free-5.13.0-web/css/all.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/fontawesome-free-5.13.0-web/js/all.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = true
preloader = "images/Logotipo2Blanco.png"
[[params.social]]
icon = "ti-whatsapp"
link = "https://wa.link/g2zc67"
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/travelinkeo/"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
[[params.social]]
icon = "ti-youtube"
link = "#"
[[params.social]]
icon = "ti-linkedin"
link = "#"
[[params.social]]
icon = "ti-dribbble"
link = "#"
[[params.social]]
icon = "ti-pinterest"
link = "#"
